name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'     # Runs daily at 01:00 UTC
  workflow_dispatch:         # Allows manual trigger

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Sync master branch
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: erikyu01
          repo: mes-qc-db-backup
          base: master
          head: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
